/*
 * Heads Up! — Template Card Packs
 * --------------------------------
 * Each pack has:
 *   id       : unique slug (used for saving progress/custom packs)
 *   category : grouping shown as a section heading on the deck picker
 *   name     : display name
 *   emoji  : icon shown on the deck
 *   color  : gradient theme for the deck + in-game background
 *   desc   : one-line description
 *   cards  : array of words/phrases players act out or describe
 *
 * Every built-in pack ships with 100+ cards. Want your own deck? Copy any
 * object below, change the cards, and give it a new id. Custom packs you build
 * in the app are stored in your browser and merged in automatically — these are
 * just the starter templates.
 */
window.HEADS_UP_PACKS = [
  {
    id: 'animals',
    category: 'Animals & Nature',
    name: 'Animals',
    emoji: '🦁',
    color: '#f59e0b',
    desc: 'From house pets to the wild savanna.',
    cards: [
      "Elephant", "Kangaroo", "Penguin", "Dolphin", "Giraffe", "Octopus",
      "Cheetah", "Koala", "Sloth", "Flamingo", "Hedgehog", "Chameleon",
      "Rhinoceros", "Platypus", "Jellyfish", "Peacock", "Hummingbird", "Walrus",
      "Meerkat", "Armadillo", "Chihuahua", "Goldfish", "Hamster", "Parrot",
      "Crocodile", "Gorilla", "Zebra", "Owl", "Bat", "Seahorse",
      "Porcupine", "Raccoon", "Otter", "Panda", "Toucan", "Camel",
      "Lobster", "Squirrel", "Woodpecker", "Tarantula", "Lion", "Tiger",
      "Bear", "Wolf", "Fox", "Deer", "Moose", "Bison",
      "Hippopotamus", "Cobra", "Python", "Iguana", "Gecko", "Turtle",
      "Tortoise", "Frog", "Toad", "Salamander", "Starfish", "Crab",
      "Jaguar", "Leopard", "Panther", "Lynx", "Hyena", "Warthog",
      "Gazelle", "Antelope", "Ostrich", "Emu", "Pelican", "Eagle",
      "Hawk", "Falcon", "Vulture", "Swan", "Duck", "Goose",
      "Turkey", "Rooster", "Pig", "Cow", "Horse", "Donkey",
      "Sheep", "Goat", "Llama", "Alpaca", "Ferret", "Skunk",
      "Beaver", "Chipmunk", "Rabbit", "Badger", "Snail", "Dragonfly",
      "Grasshopper", "Ladybug", "Ant", "Bee", "Whale", "Orca",
      "Narwhal", "Stingray", "Seal"
    ]
  },
  {
    id: 'movies',
    category: 'Entertainment',
    name: 'Blockbuster Movies',
    emoji: '🎬',
    color: '#8b5cf6',
    desc: 'Act out the biggest films of all time.',
    cards: [
      "Titanic", "Jurassic Park", "The Lion King", "Frozen", "Star Wars",
      "The Matrix", "Jaws", "Toy Story", "Avatar", "Shrek",
      "The Godfather", "Home Alone", "Ghostbusters", "E.T.", "Rocky",
      "Finding Nemo", "The Avengers", "Forrest Gump", "Grease", "Up",
      "Inception", "Gladiator", "Pirates of the Caribbean", "Back to the Future",
      "The Wizard of Oz", "Harry Potter", "Spider-Man", "The Notebook",
      "Mrs. Doubtfire", "King Kong", "Moana", "The Terminator",
      "Jumanji", "Men in Black", "Cast Away", "Twister",
      "The Dark Knight", "Black Panther", "Iron Man", "Wonder Woman",
      "The Incredibles", "Despicable Me", "Minions", "Kung Fu Panda",
      "Madagascar", "Ice Age", "Cars", "Ratatouille", "WALL-E", "Coco",
      "Encanto", "Tangled", "Beauty and the Beast", "Aladdin", "Cinderella",
      "Snow White", "The Little Mermaid", "Mulan", "Zootopia", "Inside Out",
      "Monsters, Inc.", "Brave", "The Jungle Book", "Dumbo", "Bambi",
      "101 Dalmatians", "The Lord of the Rings", "The Hobbit", "Indiana Jones",
      "Jurassic World", "The Hunger Games", "Twilight", "Deadpool",
      "Guardians of the Galaxy", "Doctor Strange", "Captain America", "Thor",
      "Aquaman", "Superman", "Batman", "Joker", "Venom", "Transformers",
      "The Fast and the Furious", "Mission: Impossible", "James Bond", "Rambo",
      "Die Hard", "The Shining", "Psycho", "Alien", "Predator", "The Exorcist",
      "Halloween", "Scream", "It", "A Quiet Place", "Get Out", "La La Land",
      "The Greatest Showman", "Mamma Mia", "Dirty Dancing", "The Sound of Music",
      "Mary Poppins"
    ]
  },
  {
    id: 'celebrities',
    category: 'People & History',
    name: 'Celebrities',
    emoji: '⭐',
    color: '#ec4899',
    desc: 'Famous faces and household names.',
    cards: [
      "Beyoncé", "Tom Hanks", "Oprah Winfrey", "Dwayne Johnson", "Taylor Swift",
      "Morgan Freeman", "Lady Gaga", "Leonardo DiCaprio", "Ariana Grande",
      "Will Smith", "Adele", "Keanu Reeves", "Rihanna", "Snoop Dogg",
      "Ellen DeGeneres", "Bad Bunny", "Zendaya", "Elon Musk", "Serena Williams",
      "Ryan Reynolds", "Billie Eilish", "Jennifer Lawrence", "Drake",
      "Meryl Streep", "Justin Bieber", "Emma Watson", "Kanye West",
      "Cristiano Ronaldo", "Selena Gomez", "Bruno Mars", "Gordon Ramsay",
      "Kim Kardashian", "Post Malone", "Scarlett Johansson", "Brad Pitt",
      "Angelina Jolie", "Johnny Depp", "Robert Downey Jr.", "Chris Hemsworth",
      "Chris Evans", "Chris Pratt", "Tom Cruise", "Denzel Washington",
      "Samuel L. Jackson", "Jackie Chan", "Arnold Schwarzenegger", "Jim Carrey",
      "Eddie Murphy", "Kevin Hart", "Chris Rock", "Jerry Seinfeld",
      "Steve Carell", "Jennifer Aniston", "Sandra Bullock", "Julia Roberts",
      "Nicole Kidman", "Reese Witherspoon", "Anne Hathaway", "Natalie Portman",
      "Emma Stone", "Margot Robbie", "Gal Gadot", "Halle Berry", "Viola Davis",
      "Michael Jordan", "LeBron James", "Lionel Messi", "Tom Brady",
      "Usain Bolt", "Tiger Woods", "Muhammad Ali", "Shaquille O'Neal",
      "Kobe Bryant", "David Beckham", "Madonna", "Elton John", "Paul McCartney",
      "Mick Jagger", "Bob Marley", "Michael Jackson", "Elvis Presley",
      "Freddie Mercury", "Whitney Houston", "Mariah Carey", "Katy Perry",
      "Shakira", "Jennifer Lopez", "Nicki Minaj", "Cardi B", "Ed Sheeran",
      "Harry Styles", "Justin Timberlake", "Miley Cyrus", "Dua Lipa",
      "The Weeknd", "Kendrick Lamar", "Jay-Z", "Eminem", "Barack Obama",
      "Dolly Parton", "Simon Cowell", "Betty White", "Jimmy Fallon"
    ]
  },
  {
    id: 'charades',
    category: 'Play & Party',
    name: 'Act It Out',
    emoji: '🎭',
    color: '#10b981',
    desc: 'Classic charades — actions & activities.',
    cards: [
      "Brushing your teeth", "Riding a horse", "Swimming", "Bowling",
      "Playing guitar", "Taking a selfie", "Sneezing", "Chopping wood",
      "Fishing", "Dancing ballet", "Boxing", "Juggling", "Yoga",
      "Doing laundry", "Flying a kite", "Milking a cow", "Rock climbing",
      "Playing tennis", "Conducting an orchestra", "Blowing out candles",
      "Tying your shoes", "Shooting a bow", "Skateboarding", "Painting a wall",
      "Vacuuming", "Golf swing", "Jumping rope", "Eating spaghetti",
      "Applying makeup", "Karate chop", "Snorkeling", "Air guitar",
      "Making a snow angel", "Cracking an egg", "Washing dishes",
      "Mowing the lawn", "Raking leaves", "Shoveling snow", "Building a sandcastle",
      "Roasting marshmallows", "Setting up a tent", "Paddling a canoe",
      "Water skiing", "Ice skating", "Riding a bike", "Driving a car",
      "Parallel parking", "Hailing a taxi", "Waiting for a bus", "Reading a book",
      "Writing a letter", "Typing on a keyboard", "Answering the phone",
      "Taking a photo", "Playing the piano", "Playing the drums",
      "Playing the violin", "Playing the trumpet", "Singing karaoke",
      "Break dancing", "Doing the moonwalk", "Line dancing", "Doing a cartwheel",
      "Hula hooping", "Lifting weights", "Doing push-ups", "Running a marathon",
      "Serving a volleyball", "Shooting a basketball", "Kicking a soccer ball",
      "Swinging a bat", "Throwing a football", "Doing a handstand",
      "Climbing a ladder", "Hammering a nail", "Sawing wood",
      "Screwing in a lightbulb", "Painting a picture", "Sculpting clay",
      "Knitting a scarf", "Sewing a button", "Ironing a shirt", "Folding laundry",
      "Making a bed", "Sweeping the floor", "Watering plants", "Planting seeds",
      "Picking apples", "Feeding a baby", "Rocking a baby", "Walking a dog",
      "Grooming a cat", "Petting a puppy", "Scratching an itch",
      "Putting on socks", "Zipping a jacket", "Buttoning a coat",
      "Brushing your hair", "Shaving", "Flossing"
    ]
  },
  {
    id: 'food',
    category: 'Food, Home & Work',
    name: 'Food & Drink',
    emoji: '🍕',
    color: '#ef4444',
    desc: 'Tasty bites and drinks to describe.',
    cards: [
      "Pizza", "Sushi", "Tacos", "Ice cream", "Spaghetti", "Pancakes",
      "Hamburger", "Popcorn", "Cotton candy", "Guacamole", "Ramen",
      "Croissant", "Watermelon", "Nachos", "Cheesecake", "Smoothie",
      "Pretzel", "Dumplings", "Bacon", "Cupcake", "Hot dog", "Waffles",
      "Burrito", "Milkshake", "Donut", "French fries", "Lasagna",
      "Pineapple", "Coffee", "Marshmallow", "Meatball", "Bubble tea",
      "Corn dog", "Avocado toast", "Steak", "Fried chicken", "Chicken wings",
      "Grilled cheese", "Macaroni and cheese", "Mashed potatoes",
      "Fish and chips", "Clam chowder", "Tomato soup", "Caesar salad",
      "Spring rolls", "Fried rice", "Pad thai", "Pho", "Curry", "Falafel",
      "Hummus", "Kebab", "Gyro", "Quesadilla", "Enchiladas", "Tamales",
      "Churros", "Flan", "Tiramisu", "Brownie", "Chocolate chip cookie",
      "Apple pie", "Pumpkin pie", "Banana bread", "Bagel", "Muffin", "Scone",
      "French toast", "Omelette", "Scrambled eggs", "Cereal", "Oatmeal",
      "Yogurt", "Granola", "Peanut butter", "Jelly", "Honey", "Maple syrup",
      "Ketchup", "Mustard", "Mayonnaise", "Salsa", "Ranch dressing",
      "Barbecue sauce", "Strawberry", "Banana", "Grapes", "Orange", "Mango",
      "Blueberry", "Cherry", "Peach", "Lemon", "Coconut", "Broccoli", "Carrot",
      "Corn on the cob", "Pickle", "Lemonade", "Hot chocolate", "Iced tea",
      "Cheeseburger", "Onion rings"
    ]
  },
  {
    id: 'sports',
    category: 'Play & Party',
    name: 'Sports',
    emoji: '⚽',
    color: '#3b82f6',
    desc: 'Games, moves, and athletes.',
    cards: [
      "Basketball", "Soccer", "Tennis", "Golf", "Baseball", "Surfing",
      "Boxing", "Skiing", "Gymnastics", "Volleyball", "Hockey", "Cricket",
      "Archery", "Wrestling", "Table tennis", "Rugby", "Figure skating",
      "Weightlifting", "Fencing", "Bowling", "Rowing", "Snowboarding",
      "Badminton", "Marathon", "Diving", "Karate", "Curling", "Sumo",
      "Slam dunk", "Home run", "Touchdown", "Penalty kick", "Hat trick",
      "Pole vault", "American football", "Ice hockey", "Field hockey",
      "Lacrosse", "Water polo", "Handball", "Squash", "Racquetball",
      "Dodgeball", "Kickball", "Softball", "Cycling", "Mountain biking", "BMX",
      "Motocross", "Formula 1", "NASCAR", "Horse racing", "Polo", "Judo",
      "Taekwondo", "Kung fu", "Kickboxing", "Mixed martial arts", "Sailing",
      "Kayaking", "Canoeing", "Rafting", "Windsurfing", "Kitesurfing",
      "Scuba diving", "Snorkeling", "Water skiing", "Wakeboarding",
      "Skateboarding", "Rollerblading", "Ice climbing", "Rock climbing",
      "Bouldering", "Hiking", "Skydiving", "Bungee jumping", "Paragliding",
      "Hang gliding", "Zip lining", "Discus", "Javelin", "Shot put",
      "High jump", "Long jump", "Hurdles", "Sprinting", "Relay race",
      "Triathlon", "Decathlon", "Cross-country", "Speed skating", "Bobsled",
      "Luge", "Ski jumping", "Biathlon", "Slalom", "Half-pipe", "Free throw",
      "Three-pointer", "Alley-oop"
    ]
  },
  {
    id: 'music',
    category: 'Entertainment',
    name: 'Hum That Tune',
    emoji: '🎵',
    color: '#a855f7',
    desc: 'Sing, hum, or dance out these hits.',
    cards: [
      "Happy Birthday", "Bohemian Rhapsody", "Baby Shark", "Sweet Caroline",
      "YMCA", "Bad Guy", "Rolling in the Deep", "Shake It Off", "Uptown Funk",
      "Thriller", "Wonderwall", "Despacito", "Smells Like Teen Spirit",
      "Dancing Queen", "Old Town Road", "Livin' on a Prayer", "Hey Jude",
      "Twinkle Twinkle Little Star", "We Will Rock You", "Single Ladies",
      "Take On Me", "Africa", "Blinding Lights", "Macarena", "Toxic",
      "Sweet Home Alabama", "I Will Survive", "Don't Stop Believin'", "Wannabe",
      "Party in the U.S.A.", "Billie Jean", "Beat It", "Like a Prayer",
      "Like a Virgin", "I Wanna Dance with Somebody",
      "Girls Just Want to Have Fun", "Every Breath You Take", "Don't Stop Me Now",
      "We Are the Champions", "Another One Bites the Dust", "Stairway to Heaven",
      "Hotel California", "Imagine", "Let It Be", "Yesterday",
      "Here Comes the Sun", "Purple Rain", "Superstition", "Respect",
      "What's Going On", "Jailhouse Rock", "Johnny B. Goode", "Ring of Fire",
      "Sweet Child o' Mine", "Livin' la Vida Loca", "Baby One More Time",
      "Since U Been Gone", "Umbrella", "Poker Face", "Bad Romance", "Firework",
      "Roar", "Halo", "Crazy in Love", "Uptown Girl", "Piano Man",
      "Sweet Dreams", "Careless Whisper", "Tainted Love", "Come On Eileen",
      "Mr. Brightside", "Seven Nation Army", "Viva la Vida", "Clocks",
      "Someone Like You", "Hello", "Shallow", "Shape of You", "Perfect",
      "Thinking Out Loud", "Happy", "Get Lucky", "Can't Stop the Feeling",
      "24K Magic", "Levitating", "Watermelon Sugar", "As It Was", "Cruel Summer",
      "Anti-Hero", "Flowers", "Dynamite", "Butter", "Gangnam Style",
      "Call Me Maybe", "Sugar", "Counting Stars", "Radioactive", "Believer",
      "Havana", "Señorita"
    ]
  },
  {
    id: 'places',
    category: 'World & Science',
    name: 'Around the World',
    emoji: '🌍',
    color: '#14b8a6',
    desc: 'Cities, countries, and landmarks.',
    cards: [
      "Eiffel Tower", "Egypt", "Great Wall of China", "New York City",
      "Amazon Rainforest", "Mount Everest", "Venice", "The Sahara Desert",
      "Statue of Liberty", "Big Ben", "Grand Canyon", "Tokyo", "Niagara Falls",
      "Australia", "Antarctica", "Rome", "Hawaii", "The Pyramids",
      "Times Square", "Hollywood", "Machu Picchu", "The Leaning Tower of Pisa",
      "Mount Rushmore", "Dubai", "Iceland", "Brazil", "The Golden Gate Bridge",
      "Stonehenge", "Bali", "Las Vegas", "The Colosseum", "Paris", "London",
      "Berlin", "Madrid", "Barcelona", "Amsterdam", "Athens", "Istanbul",
      "Moscow", "Beijing", "Shanghai", "Hong Kong", "Singapore", "Bangkok",
      "Seoul", "Mumbai", "Cairo", "Cape Town", "Nairobi", "Rio de Janeiro",
      "Buenos Aires", "Mexico City", "Toronto", "Vancouver", "Chicago",
      "Los Angeles", "San Francisco", "Miami", "Boston", "Seattle",
      "New Orleans", "Washington D.C.", "Sydney", "Melbourne", "Auckland",
      "Dublin", "Edinburgh", "Prague", "Vienna", "Budapest", "Lisbon",
      "Stockholm", "Copenhagen", "Oslo", "Helsinki", "Reykjavik", "Zurich",
      "Geneva", "Brussels", "The Taj Mahal", "Mount Fuji",
      "The Sydney Opera House", "Christ the Redeemer", "The Great Barrier Reef",
      "The Amazon River", "The Nile", "Victoria Falls", "The Alps",
      "The Rocky Mountains", "Yellowstone", "Mount Kilimanjaro", "The Dead Sea",
      "The Panama Canal", "The Vatican", "Buckingham Palace", "The White House",
      "The Empire State Building", "Angkor Wat", "Petra", "Santorini"
    ]
  },
  {
    id: 'kids',
    category: 'Kids & Family',
    name: 'Kids & Family',
    emoji: '🧸',
    color: '#f97316',
    desc: 'Easy, friendly words for all ages.',
    cards: [
      "Dog", "Cat", "Rainbow", "Balloon", "Dinosaur", "Superhero", "Robot",
      "Butterfly", "Cookie", "Bicycle", "Snowman", "Fire truck", "Teddy bear",
      "Rocket ship", "Mermaid", "Pirate", "Wizard", "Ice cream cone",
      "Bubbles", "Puppy", "Kite", "Clown", "Frog", "Dragon", "Princess",
      "Train", "Tooth fairy", "Unicorn", "Sandcastle", "Ladybug",
      "Cupcake", "Astronaut", "Piggy bank", "Umbrella", "Sun", "Moon", "Star",
      "Cloud", "Tree", "Flower", "Apple", "Banana", "Ball", "Kitten",
      "Bunny", "Duck", "Chick", "Cow", "Pig", "Horse", "Sheep", "Fish",
      "Turtle", "Bird", "Bee", "Spider", "Snail", "Worm", "Ant", "Caterpillar",
      "Elephant", "Lion", "Tiger", "Monkey", "Bear", "Penguin", "Owl", "Whale",
      "Shark", "Dolphin", "Crab", "Starfish", "Octopus", "Seahorse", "Car",
      "Bus", "Boat", "Airplane", "Helicopter", "Truck", "Tractor", "Rocket",
      "Scooter", "Wagon", "Hat", "Shoe", "Sock", "Mitten", "Crayon", "Book",
      "Drum", "Guitar", "Whistle", "Bell", "Cake", "Candy", "Lollipop",
      "Popsicle", "Slide", "Swing", "Seesaw", "Sandbox"
    ]
  },
  {
    id: 'tvshows',
    category: 'Entertainment',
    name: 'TV Shows',
    emoji: '📺',
    color: '#6366f1',
    desc: 'Binge-worthy series to act out.',
    cards: [
      "Friends", "The Office", "Stranger Things", "Game of Thrones",
      "Breaking Bad", "SpongeBob SquarePants", "The Simpsons", "Seinfeld",
      "Squid Game", "The Mandalorian", "Sesame Street", "Grey's Anatomy",
      "Wednesday", "The Crown", "Peaky Blinders", "Ted Lasso", "Sherlock",
      "Modern Family", "Survivor", "Jeopardy!", "Bluey", "The Walking Dead",
      "Black Mirror", "Downton Abbey", "Family Guy", "Cobra Kai",
      "The Big Bang Theory", "Scooby-Doo", "Bridgerton", "Pokémon",
      "How I Met Your Mother", "Parks and Recreation", "Brooklyn Nine-Nine",
      "It's Always Sunny in Philadelphia", "Community", "Arrested Development",
      "Curb Your Enthusiasm", "Frasier", "Cheers", "Fresh Prince of Bel-Air",
      "Full House", "Everybody Loves Raymond", "Malcolm in the Middle",
      "That '70s Show", "Married... with Children", "Roseanne",
      "The Golden Girls", "M*A*S*H", "I Love Lucy", "The Twilight Zone", "Lost",
      "24", "Prison Break", "Dexter", "The Wire", "The Sopranos", "Mad Men",
      "House of Cards", "Ozark", "Better Call Saul", "Fargo", "True Detective",
      "Westworld", "The Last of Us", "House of the Dragon", "The Witcher",
      "Vikings", "Outlander", "The Boys", "Loki", "WandaVision",
      "The Umbrella Academy", "Money Heist", "Dark", "Narcos", "Sex Education",
      "Never Have I Ever", "Emily in Paris", "The Queen's Gambit", "Beef",
      "Euphoria", "Riverdale", "Gossip Girl", "Pretty Little Liars",
      "13 Reasons Why", "Glee", "Gilmore Girls", "One Tree Hill",
      "Dawson's Creek", "Vampire Diaries", "Avatar: The Last Airbender",
      "Rick and Morty", "BoJack Horseman", "Adventure Time", "Gravity Falls",
      "Phineas and Ferb", "Teen Titans", "Looney Tunes", "Tom and Jerry",
      "The Flintstones", "South Park"
    ]
  },
  {
    id: 'videogames',
    category: 'Entertainment',
    name: 'Video Games',
    emoji: '🎮',
    color: '#22c55e',
    desc: 'Iconic games, consoles, and characters.',
    cards: [
      "Super Mario Bros.", "Pac-Man", "Tetris", "Minecraft", "Fortnite",
      "The Legend of Zelda", "Sonic the Hedgehog", "Donkey Kong", "Space Invaders",
      "Pong", "Call of Duty", "Grand Theft Auto", "Halo", "Pokémon",
      "Animal Crossing", "Among Us", "Fall Guys", "Roblox", "Candy Crush",
      "Angry Birds", "Mario Kart", "Super Smash Bros.", "Street Fighter",
      "Mortal Kombat", "Tekken", "FIFA", "Madden NFL", "NBA 2K", "Rocket League",
      "Overwatch", "League of Legends", "Dota 2", "Valorant", "Counter-Strike",
      "Apex Legends", "PUBG", "World of Warcraft", "Diablo", "StarCraft",
      "The Sims", "SimCity", "Civilization", "Age of Empires", "Fallout",
      "The Elder Scrolls", "Skyrim", "Red Dead Redemption", "The Last of Us",
      "Uncharted", "God of War", "Horizon Zero Dawn", "Assassin's Creed",
      "Far Cry", "Watch Dogs", "Tomb Raider", "Resident Evil", "Silent Hill",
      "Dead Space", "Metal Gear Solid", "Splinter Cell", "BioShock", "Half-Life",
      "Portal", "Left 4 Dead", "Team Fortress 2", "Doom", "Wolfenstein",
      "Quake", "Duke Nukem", "Borderlands", "Destiny", "Mass Effect",
      "Dragon Age", "Final Fantasy", "Kingdom Hearts", "Chrono Trigger",
      "Dark Souls", "Elden Ring", "Bloodborne", "Sekiro", "Cuphead",
      "Hollow Knight", "Celeste", "Stardew Valley", "Terraria", "Undertale",
      "Cyberpunk 2077", "The Witcher 3", "Ghost of Tsushima", "Death Stranding",
      "Metroid", "Kirby", "Star Fox", "Pikmin", "Splatoon", "Luigi's Mansion",
      "Super Mario Odyssey", "Breath of the Wild", "Crash Bandicoot", "Spyro",
      "Rayman", "Mega Man", "Castlevania", "Frogger", "Centipede"
    ]
  },
  {
    id: 'disney',
    category: 'Entertainment',
    name: 'Disney & Pixar',
    emoji: '🏰',
    color: '#0ea5e9',
    desc: 'Beloved characters from the magic kingdom.',
    cards: [
      "Mickey Mouse", "Minnie Mouse", "Donald Duck", "Goofy", "Pluto",
      "Daisy Duck", "Cinderella", "Snow White", "Sleeping Beauty", "Belle",
      "Ariel", "Jasmine", "Aladdin", "Mulan", "Pocahontas", "Tiana",
      "Rapunzel", "Merida", "Moana", "Elsa", "Anna", "Olaf", "Simba",
      "Mufasa", "Scar", "Timon", "Pumbaa", "Nala", "Zazu", "Rafiki", "Woody",
      "Buzz Lightyear", "Jessie", "Rex", "Mr. Potato Head", "Slinky Dog",
      "Nemo", "Dory", "Marlin", "Crush", "Lightning McQueen", "Mater",
      "Mike Wazowski", "James P. Sullivan", "Boo", "Remy", "WALL-E", "EVE",
      "Carl Fredricksen", "Dug", "Joy", "Sadness", "Anger", "Fear", "Disgust",
      "Riley", "Wreck-It Ralph", "Vanellope", "Baymax", "Hiro", "Judy Hopps",
      "Nick Wilde", "Bruno", "Mirabel", "Peter Pan", "Tinker Bell",
      "Captain Hook", "Winnie the Pooh", "Tigger", "Eeyore", "Piglet", "Dumbo",
      "Bambi", "Thumper", "Pinocchio", "Jiminy Cricket", "Alice", "Cheshire Cat",
      "Mad Hatter", "Queen of Hearts", "Maleficent", "Ursula", "Cruella de Vil",
      "Gaston", "Jafar", "Hades", "Genie", "Stitch", "Lilo", "Baloo", "Mowgli",
      "Bagheera", "Sebastian", "Flounder", "Kristoff", "Sven", "Hercules",
      "Megara", "Kuzco", "Frozone", "Mr. Incredible", "Elastigirl", "Dash",
      "Violet", "Edna Mode"
    ]
  },
  {
    id: 'superheroes',
    category: 'Entertainment',
    name: 'Superheroes & Villains',
    emoji: '🦸',
    color: '#dc2626',
    desc: 'Caped crusaders and their arch-nemeses.',
    cards: [
      "Superman", "Batman", "Spider-Man", "Iron Man", "Captain America", "Thor",
      "Hulk", "Black Widow", "Hawkeye", "Wonder Woman", "The Flash", "Aquaman",
      "Green Lantern", "Cyborg", "Wolverine", "Deadpool", "Black Panther",
      "Doctor Strange", "Scarlet Witch", "Vision", "Ant-Man", "The Wasp",
      "Star-Lord", "Gamora", "Groot", "Rocket Raccoon", "Drax", "Nebula",
      "Falcon", "Winter Soldier", "Nick Fury", "Loki", "Thanos", "Ultron",
      "Green Goblin", "Doctor Octopus", "Venom", "Carnage", "Mysterio",
      "Vulture", "Magneto", "Professor X", "Cyclops", "Jean Grey", "Storm",
      "Beast", "Nightcrawler", "Rogue", "Gambit", "Mystique", "Daredevil",
      "Punisher", "Ghost Rider", "Blade", "Silver Surfer", "Mister Fantastic",
      "Invisible Woman", "Human Torch", "The Thing", "Doctor Doom", "Nova",
      "She-Hulk", "Moon Knight", "Ms. Marvel", "Captain Marvel", "Shang-Chi",
      "Robin", "Nightwing", "Batgirl", "Alfred", "Joker", "Harley Quinn",
      "The Riddler", "Two-Face", "The Penguin", "Catwoman", "Bane", "Poison Ivy",
      "Mr. Freeze", "Scarecrow", "Lex Luthor", "Brainiac", "Darkseid",
      "Supergirl", "Shazam", "Martian Manhunter", "Green Arrow", "Black Canary",
      "Hawkgirl", "Zatanna", "Doomsday", "Reverse-Flash", "Sinestro",
      "Deathstroke", "The Atom", "Firestorm", "Blue Beetle", "Static Shock",
      "Hellboy", "Spawn", "Invincible", "Homelander", "Doctor Manhattan"
    ]
  },
  {
    id: 'magic',
    category: 'Entertainment',
    name: 'Magic & Fantasy',
    emoji: '🧙',
    color: '#7c3aed',
    desc: 'Wizards, creatures, spells, and myth.',
    cards: [
      "Wizard", "Witch", "Sorcerer", "Warlock", "Enchantress", "Mage",
      "Spellbook", "Magic wand", "Crystal ball", "Potion", "Cauldron",
      "Broomstick", "Wizard's hat", "Magic carpet", "Genie in a lamp",
      "Fairy godmother", "Dragon", "Unicorn", "Phoenix", "Griffin", "Centaur",
      "Minotaur", "Mermaid", "Elf", "Dwarf", "Goblin", "Troll", "Ogre", "Orc",
      "Fairy", "Pixie", "Gnome", "Leprechaun", "Werewolf", "Vampire", "Zombie",
      "Ghost", "Skeleton", "Banshee", "Kraken", "Basilisk", "Hydra", "Cyclops",
      "Pegasus", "Sphinx", "Chimera", "Gargoyle", "Golem", "Djinn", "Yeti",
      "Loch Ness Monster", "Bigfoot", "Fairy dust", "Invisibility cloak",
      "Enchanted forest", "Wizard tower", "Dungeon", "Castle", "Moat",
      "Dragon's lair", "Treasure chest", "Magic mirror", "Spellcasting",
      "Fireball", "Lightning bolt", "Teleportation", "Levitation",
      "Shapeshifting", "Curse", "Hex", "Enchantment", "Prophecy", "Wizard duel",
      "Excalibur", "Merlin", "King Arthur", "Camelot", "Round Table", "Gandalf",
      "Hobbit", "The One Ring", "Elrond", "Frodo", "Middle-earth",
      "Harry Potter", "Hermione Granger", "Ron Weasley", "Dumbledore",
      "Voldemort", "Hogwarts", "Quidditch", "Sorting Hat", "Golden Snitch",
      "Fairy tale", "Wizard's staff", "Enchanted rose", "Magic beans",
      "Wishing well", "Shooting star", "Spellbound", "Magic spell"
    ]
  },
  {
    id: 'jobs',
    category: 'Food, Home & Work',
    name: 'Jobs & Professions',
    emoji: '👷',
    color: '#0891b2',
    desc: 'What do you want to be when you grow up?',
    cards: [
      "Doctor", "Nurse", "Surgeon", "Dentist", "Veterinarian", "Pharmacist",
      "Paramedic", "Firefighter", "Police officer", "Detective", "Lawyer",
      "Judge", "Teacher", "Professor", "Principal", "Librarian", "Scientist",
      "Engineer", "Architect", "Electrician", "Plumber", "Carpenter", "Mechanic",
      "Welder", "Construction worker", "Farmer", "Fisherman", "Rancher",
      "Gardener", "Chef", "Baker", "Butcher", "Waiter", "Bartender", "Barista",
      "Cashier", "Salesperson", "Manager", "Accountant", "Banker", "Economist",
      "Stockbroker", "Real estate agent", "Insurance agent", "Receptionist",
      "Secretary", "Administrative assistant", "Human resources manager",
      "Recruiter", "Pilot", "Flight attendant", "Air traffic controller",
      "Astronaut", "Sailor", "Ship captain", "Truck driver", "Bus driver",
      "Taxi driver", "Train conductor", "Mail carrier", "Delivery driver",
      "Journalist", "Reporter", "News anchor", "Photographer", "Editor",
      "Author", "Poet", "Translator", "Actor", "Musician", "Singer", "Dancer",
      "Comedian", "Magician", "Sculptor", "Fashion designer", "Interior designer",
      "Graphic designer", "Software developer", "Data scientist", "Web designer",
      "IT technician", "Video game developer", "Social media manager",
      "Marketing manager", "Advertiser", "Public relations specialist",
      "Event planner", "Coach", "Personal trainer", "Yoga instructor",
      "Lifeguard", "Referee", "Tour guide", "Hotel manager", "Housekeeper",
      "Janitor", "Barber", "Hairdresser", "Makeup artist", "Optician"
    ]
  },
  {
    id: 'household',
    category: 'Food, Home & Work',
    name: 'Around the House',
    emoji: '🏠',
    color: '#d97706',
    desc: 'Everyday objects from every room.',
    cards: [
      "Sofa", "Armchair", "Coffee table", "Dining table", "Chair", "Bed",
      "Pillow", "Blanket", "Mattress", "Dresser", "Wardrobe", "Nightstand",
      "Bookshelf", "Desk", "Lamp", "Ceiling fan", "Chandelier", "Curtains",
      "Blinds", "Rug", "Carpet", "Doormat", "Mirror", "Picture frame", "Clock",
      "Vase", "Candle", "Television", "Remote control", "Refrigerator",
      "Freezer", "Oven", "Stove", "Microwave", "Toaster", "Blender", "Kettle",
      "Coffee maker", "Dishwasher", "Sink", "Faucet", "Cutting board",
      "Frying pan", "Saucepan", "Spatula", "Whisk", "Ladle", "Colander",
      "Rolling pin", "Plate", "Bowl", "Cup", "Mug", "Glass", "Fork", "Knife",
      "Spoon", "Napkin", "Tablecloth", "Trash can", "Broom", "Dustpan", "Mop",
      "Bucket", "Vacuum cleaner", "Sponge", "Dish soap", "Paper towels",
      "Laundry basket", "Washing machine", "Dryer", "Iron", "Ironing board",
      "Clothes hanger", "Clothespin", "Towel", "Bath mat", "Shower curtain",
      "Bathtub", "Shower", "Toilet", "Toilet paper", "Toothbrush", "Toothpaste",
      "Soap", "Shampoo", "Hair dryer", "Razor", "Comb", "Alarm clock",
      "Light switch", "Doorknob", "Key", "Coat rack", "Flower pot",
      "Watering can", "Toolbox", "Hammer", "Screwdriver", "Flashlight",
      "Smoke detector"
    ]
  },
  {
    id: 'science',
    category: 'World & Science',
    name: 'Science & Space',
    emoji: '🔬',
    color: '#2563eb',
    desc: 'Atoms, planets, and everything between.',
    cards: [
      "Atom", "Molecule", "Cell", "DNA", "Gravity", "Magnet", "Electricity",
      "Energy", "Force", "Motion", "Velocity", "Acceleration", "Friction",
      "Mass", "Density", "Pressure", "Temperature", "Heat", "Light", "Sound",
      "Electron", "Proton", "Neutron", "Nucleus", "Element", "Periodic table",
      "Hydrogen", "Oxygen", "Carbon", "Helium", "Chemical reaction", "Acid",
      "Base", "Crystal", "Magnetism", "Circuit", "Battery", "Laser",
      "Microscope", "Telescope", "Sun", "Moon", "Earth", "Mercury", "Venus",
      "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto", "Asteroid",
      "Comet", "Meteor", "Meteorite", "Galaxy", "Milky Way", "Black hole",
      "Supernova", "Nebula", "Star", "Constellation", "Solar system", "Orbit",
      "Eclipse", "Solar flare", "Astronaut", "Spacesuit", "Rocket",
      "Space shuttle", "Satellite", "Space station", "Rover", "Space probe",
      "Big Bang", "Universe", "Light-year", "Wormhole", "Alien", "UFO",
      "Volcano", "Earthquake", "Tsunami", "Tornado", "Hurricane", "Lightning",
      "Rainbow", "Fossil", "Evolution", "Photosynthesis", "Ecosystem",
      "Food chain", "Bacteria", "Virus", "Vaccine", "Genome", "Cloning",
      "Artificial intelligence", "Test tube", "Bunsen burner", "Centrifuge"
    ]
  },
  {
    id: 'history',
    category: 'People & History',
    name: 'History Makers',
    emoji: '📜',
    color: '#b45309',
    desc: 'Figures who shaped the world.',
    cards: [
      "Albert Einstein", "Isaac Newton", "Galileo Galilei", "Charles Darwin",
      "Marie Curie", "Nikola Tesla", "Thomas Edison", "Leonardo da Vinci",
      "Michelangelo", "William Shakespeare", "Cleopatra", "Julius Caesar",
      "Alexander the Great", "Napoleon Bonaparte", "Genghis Khan",
      "Christopher Columbus", "Ferdinand Magellan", "Marco Polo",
      "Amelia Earhart", "Neil Armstrong", "Yuri Gagarin", "George Washington",
      "Abraham Lincoln", "Thomas Jefferson", "Benjamin Franklin",
      "Theodore Roosevelt", "Franklin D. Roosevelt", "John F. Kennedy",
      "Winston Churchill", "Queen Victoria", "Queen Elizabeth I", "Henry VIII",
      "King Tutankhamun", "Mahatma Gandhi", "Nelson Mandela",
      "Martin Luther King Jr.", "Rosa Parks", "Harriet Tubman",
      "Frederick Douglass", "Susan B. Anthony", "Joan of Arc",
      "Florence Nightingale", "Mother Teresa", "Anne Frank", "Helen Keller",
      "Louis Pasteur", "Alexander Fleming", "Sigmund Freud", "Aristotle",
      "Plato", "Socrates", "Pythagoras", "Archimedes", "Confucius", "Homer",
      "Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Johann Sebastian Bach",
      "Vincent van Gogh", "Pablo Picasso", "Claude Monet", "Rembrandt",
      "Frida Kahlo", "Walt Disney", "Henry Ford", "Steve Jobs", "Bill Gates",
      "Alan Turing", "Charles Dickens", "Mark Twain", "Jane Austen",
      "Edgar Allan Poe", "Ernest Hemingway", "Maya Angelou", "Karl Marx",
      "Che Guevara", "Copernicus", "Johannes Kepler", "Stephen Hawking",
      "Rosalind Franklin", "Ada Lovelace", "Grace Hopper", "Katherine Johnson",
      "Sacagawea", "Sitting Bull", "Crazy Horse", "Geronimo", "Ramses II",
      "Nefertiti", "Hannibal", "Attila the Hun", "Leif Erikson", "Charlemagne",
      "Malala Yousafzai", "Wright Brothers", "Ronald Reagan", "Mansa Musa",
      "Catherine the Great", "Emmeline Pankhurst", "Jackie Robinson"
    ]
  },
  {
    id: 'eighties',
    category: 'Throwback',
    name: "The '80s",
    emoji: '📼',
    color: '#db2777',
    desc: 'Totally rad movies, music, and fads.',
    cards: [
      "E.T.", "Back to the Future", "Ghostbusters", "The Breakfast Club",
      "Ferris Bueller's Day Off", "Top Gun", "Die Hard", "Gremlins",
      "The Goonies", "Beetlejuice", "Dirty Dancing", "Flashdance",
      "The Karate Kid", "Rain Man", "Who Framed Roger Rabbit", "Labyrinth",
      "Blade Runner", "The Terminator", "Michael Jackson", "Madonna", "Prince",
      "Whitney Houston", "Cyndi Lauper", "Duran Duran", "Bon Jovi",
      "Guns N' Roses", "Wham!", "Culture Club", "Tears for Fears", "A-ha",
      "Def Leppard", "Run-DMC", "David Bowie", "Phil Collins", "Lionel Richie",
      "Billy Idol", "Miami Vice", "The A-Team", "Knight Rider", "Cheers",
      "MacGyver", "Family Ties", "The Cosby Show", "ALF", "He-Man",
      "Thundercats", "Transformers", "Care Bears", "My Little Pony", "Voltron",
      "Rubik's Cube", "Cabbage Patch Kids", "Teddy Ruxpin", "Garbage Pail Kids",
      "Pac-Man", "Nintendo", "Game Boy", "Atari", "Simon", "Speak & Spell",
      "View-Master", "Etch A Sketch", "Lite-Brite", "Pound Puppies", "My Buddy",
      "Nerf", "Walkman", "Boombox", "Cassette tape", "VHS tape", "DeLorean",
      "MTV", "Commodore 64", "Floppy disk", "Trapper Keeper", "Slap bracelet",
      "Jelly shoes", "Leg warmers", "Shoulder pads", "Mullet", "Big hair",
      "Neon clothing", "Parachute pants", "Acid-wash jeans", "Fanny pack",
      "Swatch watch", "Roller skates", "Aerobics", "Breakdancing", "Moonwalk",
      "Members Only jacket", "Ray-Ban sunglasses", "Scrunchie", "Perm",
      "Tube socks", "Windbreaker", "BMX bike", "Arcade", "Mixtape", "Hair gel"
    ]
  },
  {
    id: 'nineties',
    category: 'Throwback',
    name: "The '90s",
    emoji: '💿',
    color: '#0d9488',
    desc: 'All that and a bag of chips.',
    cards: [
      "Jurassic Park", "Titanic", "Home Alone", "The Lion King", "Toy Story",
      "Forrest Gump", "The Matrix", "Men in Black", "Mrs. Doubtfire", "Space Jam",
      "Jumanji", "The Sixth Sense", "Independence Day", "Aladdin", "Clueless",
      "Ace Ventura", "Groundhog Day", "Braveheart", "Spice Girls",
      "Backstreet Boys", "NSYNC", "Britney Spears", "Nirvana", "Pearl Jam",
      "Mariah Carey", "TLC", "Destiny's Child", "Boyz II Men",
      "Alanis Morissette", "Céline Dion", "Oasis", "Green Day", "Tupac",
      "The Notorious B.I.G.", "Hanson", "Ricky Martin", "Friends", "Seinfeld",
      "The Fresh Prince of Bel-Air", "The X-Files", "Beverly Hills 90210",
      "Saved by the Bell", "Rugrats", "Hey Arnold!", "Power Rangers",
      "Boy Meets World", "Sabrina the Teenage Witch", "ER", "Baywatch",
      "Dragon Ball Z", "Doug", "The Ren & Stimpy Show", "Frasier",
      "Married... with Children", "Tamagotchi", "Beanie Babies", "Furby",
      "Pogs", "Super Soaker", "Nintendo 64", "Sega Genesis", "PlayStation",
      "Pokémon cards", "Polly Pocket", "Skip-It", "Moon Shoes", "Lisa Frank",
      "Yo-yo", "Koosh ball", "Gak", "Easy-Bake Oven", "Bop It", "Giga Pet",
      "Sky Dancers", "Dial-up internet", "AOL", "Pager", "Discman", "Windows 95",
      "Nokia phone", "Floppy disk", "CD-ROM", "Palm Pilot", "DVD", "Screensaver",
      "Chat room", "Overalls", "Jelly sandals", "Frosted tips", "Choker",
      "Baggy jeans", "Flannel shirt", "Platform shoes", "Bucket hat",
      "Butterfly clips", "JNCO jeans", "Grunge", "Denim jacket", "Body glitter",
      "Rollerblades"
    ]
  },
  {
    id: 'twothousands',
    category: 'Throwback',
    name: 'The 2000s',
    emoji: '📱',
    color: '#e11d48',
    desc: 'Y2K, flip phones, and low-rise everything.',
    cards: [
      "Shrek", "Finding Nemo", "The Lord of the Rings", "Harry Potter",
      "Pirates of the Caribbean", "Spider-Man", "The Incredibles", "Avatar",
      "Napoleon Dynamite", "Mean Girls", "Anchorman", "Elf", "School of Rock",
      "Twilight", "Iron Man", "The Dark Knight", "Legally Blonde", "Bring It On",
      "Beyoncé", "Eminem", "50 Cent", "OutKast", "Usher", "Rihanna",
      "Justin Timberlake", "Christina Aguilera", "Black Eyed Peas", "Coldplay",
      "Linkin Park", "Kanye West", "Nelly", "Avril Lavigne", "Gwen Stefani",
      "Jay-Z", "Shakira", "Kelly Clarkson", "American Idol", "Survivor", "Lost",
      "The Office", "Desperate Housewives", "CSI", "Hannah Montana",
      "Drake & Josh", "iCarly", "The Suite Life of Zack & Cody",
      "High School Musical", "Jackass", "Punk'd", "The O.C.", "Gossip Girl",
      "Heroes", "24", "The Amazing Race", "iPod", "iPhone", "Motorola Razr",
      "MySpace", "Facebook", "YouTube", "Xbox", "PlayStation 2", "Nintendo Wii",
      "Guitar Hero", "Bratz dolls", "Webkinz", "Silly Bandz", "Sidekick phone",
      "BlackBerry", "Napster", "LimeWire", "Nintendo DS", "USB flash drive",
      "Bluetooth headset", "Crocs", "Ed Hardy", "Von Dutch hat",
      "Juicy Couture tracksuit", "Trucker hat", "Livestrong bracelet", "Emo",
      "Skinny jeans", "Ugg boots", "Popped collar", "Razor scooter", "Heelys",
      "Low-rise jeans", "Chunky highlights", "Side bangs", "Cargo shorts",
      "Studded belt", "Bedazzled jeans", "Tribal tattoo", "Bump-it",
      "Shutter shades", "Aviator sunglasses", "Fauxhawk", "Velour tracksuit",
      "Pashmina", "Rhinestones"
    ]
  }
];
